language: python
python:
  - "3.7"
services:
  - docker
install:
  - pip install --upgrade pip attrs
  - pip install -r requirements.txt
  - python setup.py install
  - docker pull pansihub/pancli
  - docker build -t scrapydd .
  - docker build -f dockerfiles/Dockerfile.develop.py3 -t scrapydd:unittest .
  - pip install nose coverage
  - pip install -U codecov
script: |
  nosetests tests --with-coverage --cover-package=scrapydd --cover-html && \
  docker run --rm -w /src -v /var/run/docker.sock:/var/run/docker.sock \
                   scrapydd:unittest nosetests tests --exe
after_success:
  - codecov
