language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
  - pip install nose coverage
  - pip install -U codecov
script: nosetests tests --with-coverage --cover-package=scrapydd --cover-html
after_success:
  - codecov
