language: python
python:
  - "2.7"
  - "3.6"
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
  - docker build -f Dockerfile.dev -t scrapydd:develop .
  - pip install nose coverage
  - pip install -U codecov
script: |
  nosetests tests --with-coverage --cover-package=scrapydd --cover-html && \
  docker run -w /scrapydd_src -v /var/run/docker.sock:/var/run/docker.sock \
               scrapydd:develop nosetests tests
after_success:
  - codecov
