language: python
python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true
services:
  - docker
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install

  - docker build -f dockerfiles/Dockerfile.develop.py2 -t scrapydd:develop.py2 .
  - docker build -f dockerfiles/Dockerfile.develop.py3 -t scrapydd:develop.py3 .
  - docker tag scrapydd:develop.py3 scrapydd:develop
  - pip install nose coverage
  - pip install -U codecov
script: |
  nosetests tests --with-coverage --cover-package=scrapydd --cover-html && \
  docker run -w /scrapydd_src -v /var/run/docker.sock:/var/run/docker.sock \
                 scrapydd:develop.py2 nosetests tests --exe && \
  docker run -w /scrapydd_src -v /var/run/docker.sock:/var/run/docker.sock \
                   scrapydd:develop.py3 nosetests tests --exe
after_success:
  - codecov
