version: '3'
services:
  scrapydd-server:
    image: "kevenli/scrapydd:develop"
    ports:
      - "6800:6800"
    volumes:
      - "/scrapydd/server:/scrapydd"
    command: scrapydd server
    environment:
      - SCRAPYDD_DEBUG=false


  scrapydd-agent:
    image: "kevenli/scrapydd:develop"
    volumes:
      - "/scrapydd/server:/scrapydd"
    links:
      - scrapydd-server
    environment:
      - SCRAPYDD_SERVER=scrapydd-server
    command: scrapydd agent
