#!/usr/bin/env bash
. /etc/rc.d/init.d/functions
PATH=/usr/local/bin:/bin:

APP_PATH="/wis/scrapydd/server"
PIDFILE="$APP_PATH/server.pid"
LOCKFILE=/var/lock/subsys/scrapydd-server
EXEFILE=/usr/local/bin/python
prog=ScrapyddServer
STOP_TIMEOUT=${STOP_TIMEOUT-10}

start(){
    echo $APP_PATH
  cd $APP_PATH
  echo $PIDFILE
  echo -n $"Starting $prog: "
  daemon --pidfile=$PIDFILE scrapydd server --pidfile=$PIDFILE --daemon
  #daemon --pidfile=$PIDFILE
  RETVAL=$?
  echo
  [ $RETVAL = 0 ] && touch $LOCKFILE
  return $RETVAL
}

stop(){
    status -p $PIDFILE $EXEFILE > /dev/null
    if [[ $? = 0 ]]; then
        echo -n $"Stopping $prog: "
        killproc -p ${PIDFILE} -d ${STOP_TIMEOUT} $EXEFILE
    else
        echo -n $"Stopping $prog:"
        success
    fi
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${LOCKFILE} ${PIDFILE}
}
ACMD="$1"
case $ACMD in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status -p ${PIDFILE} $EXEFILE
    ;;
*)
    echo $"Usage: $0 {start|stop|status|restart}"
    exit 2
esac

