version: '3.4'
services:
  pancli:
    image: pansihub/pancli

  sut:
    image: scrapydd:unittest
    working_dir: /src
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: python -m nose tests --exe
    depends_on:
      - build_unittest
      - pancli

  build_unittest:
    image: scrapydd:unittest
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.develop.py3
      network: host
    depends_on:
      - build

  build:
    image: scrapydd
    build:
      context: ..
      dockerfile: Dockerfile
      network: host
