openapi: '3.0.0'
info:
  description: |
    Node API for communication between worker and server .
  version: 1.0.0
  title: Node API
tags:
- name: node
- name: NodeSession
paths:
  /nodes:
    post:
      summary: Register a new permanent node.
      operationId: CreateNode
      tags:
      - node
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Node"
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - "node_key"
              properties:
                node_key:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
          
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/Node"
        400:
          description: Invalid parameter.
        401:
          description: Unauthenticated request.
  /nodeSessions:
    post:
      tags:
      - node
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeSession'
      responses:
        200:
          description: Sucessful Result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeSession"
        401: 
          description: Unauthenticated request.
components:
  schemas:
    Node:
      type: object
      required:
      - node_key
      properties:
        name:
          type: string
          readOnly: true
        id:
          type: integer
          format: int64
          readOnly: true
        display_name:
          type: string
          readOnly: true
        tags:
          type: array
          items:
            type: string
        node_key:
          type: string
        is_online: 
          type: boolean
          readOnly: true
        client_ip:
          type: string
          readOnly: true
    CreateNodeRequest:
      type: object
      properties:
        node:
          $ref: "#/components/schemas/Node"
    NodeSession:
      type: object
      properties:
        name:
          type: string
          example: 'nodeSessions/*'
        id:
          type: integer
          format: int64
        tags:
          type: array
          items:
            type: string
