openapi: 3.0.0
info:
  description: |
    Node API for communication between worker and server.
  version: 1.0.0
  title: Node API
tags:
- name: node
- name: NodeSession
paths:
  /nodes:
    post:
      summary: Register a new permanent node.
      operationId: CreateNode
      tags:
      - node
      parameters:
        - in: query
          name: node_key
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Node"
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                tags:
                  type: array
                  items:
                    type: string

      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref:  "#/components/schemas/Node"
        400:
          description: Invalid parameter.
        401:
          description: Unauthenticated request.
  /nodes/{nodeId}:
    get:
      tags:
      - node
      parameters:
      - in: path
        name: nodeId
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Node"
  /nodeSessions:
    post:
      tags:
      - node
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NodeSession'
      responses:
        200:
          description: Sucessful Result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeSession"
        401:
          description: Unauthenticated request.
  /nodeSessions/{nodeSessionId}:hearbeat:
    post:
      tags:
        - node
      parameters:
        - in: path
          name: nodeSessionId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                running_job_ids:
                  type: string
      responses:
        200:
          description: Successful Result
        401:
          description: Unauthenticated request
components:
  schemas:
    Node:
      type: object
      required:
      - node_key
      properties:
        name:
          type: string
          readOnly: true
        id:
          type: integer
          format: int64
          readOnly: true
        display_name:
          type: string
          readOnly: true
        tags:
          type: array
          items:
            type: string
        is_online:
          type: boolean
          readOnly: true
        client_ip:
          type: string
          readOnly: true
    NodeSession:
      type: object
      properties:
        name:
          type: string
          example: 'nodeSessions/*'
          readOnly: true
        id:
          type: integer
          format: int64
          readOnly: true
        node_id:
          type: integer
          format: int64
servers:
  - url: http://localhost:6800/v1
