# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrapydd/grpcservice/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scrapydd/grpcservice/service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\"scrapydd/grpcservice/service.proto\"\'\n\x10HeartbeatRequest\x12\x13\n\x0brunningJobs\x18\x01 \x03(\t\"S\n\x11HeartbeatResponse\x12\x13\n\x0bnodeExpired\x18\x01 \x01(\x08\x12\x10\n\x08killJobs\x18\x02 \x03(\t\x12\x17\n\x0fnewJobAvailable\x18\x03 \x01(\x08\"\x13\n\x11GetNextJobRequest\"D\n\x12GetNextJobResponse\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x0e\n\x06\x66igure\x18\x02 \x01(\t\x12\x0f\n\x07package\x18\x03 \x01(\x0c\"\x0f\n\rGetJobRequest\"\x10\n\x0eGetJobResponse\"\x12\n\x10GetJobEggRequest\"\x13\n\x11GetJobEggResponse\"P\n\x12\x43ompleteJobRequest\x12\r\n\x05jobId\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0c\n\x04logs\x18\x03 \x01(\x0c\x12\r\n\x05items\x18\x04 \x01(\x0c\"\x15\n\x13\x43ompleteJobResponse2\x8d\x02\n\x0bNodeService\x12\x32\n\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponse\x12\x35\n\nGetNextJob\x12\x12.GetNextJobRequest\x1a\x13.GetNextJobResponse\x12)\n\x06GetJob\x12\x0e.GetJobRequest\x1a\x0f.GetJobResponse\x12.\n\x06GetEgg\x12\x11.GetJobEggRequest\x1a\x11.GetJobEggRequest\x12\x38\n\x0b\x43ompleteJob\x12\x13.CompleteJobRequest\x1a\x14.CompleteJobResponseb\x06proto3')
)




_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runningJobs', full_name='HeartbeatRequest.runningJobs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=77,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeExpired', full_name='HeartbeatResponse.nodeExpired', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='killJobs', full_name='HeartbeatResponse.killJobs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newJobAvailable', full_name='HeartbeatResponse.newJobAvailable', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=162,
)


_GETNEXTJOBREQUEST = _descriptor.Descriptor(
  name='GetNextJobRequest',
  full_name='GetNextJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=183,
)


_GETNEXTJOBRESPONSE = _descriptor.Descriptor(
  name='GetNextJobResponse',
  full_name='GetNextJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobId', full_name='GetNextJobResponse.jobId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='figure', full_name='GetNextJobResponse.figure', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package', full_name='GetNextJobResponse.package', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=253,
)


_GETJOBREQUEST = _descriptor.Descriptor(
  name='GetJobRequest',
  full_name='GetJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=270,
)


_GETJOBRESPONSE = _descriptor.Descriptor(
  name='GetJobResponse',
  full_name='GetJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=288,
)


_GETJOBEGGREQUEST = _descriptor.Descriptor(
  name='GetJobEggRequest',
  full_name='GetJobEggRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=308,
)


_GETJOBEGGRESPONSE = _descriptor.Descriptor(
  name='GetJobEggResponse',
  full_name='GetJobEggResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=329,
)


_COMPLETEJOBREQUEST = _descriptor.Descriptor(
  name='CompleteJobRequest',
  full_name='CompleteJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobId', full_name='CompleteJobRequest.jobId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='CompleteJobRequest.status', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logs', full_name='CompleteJobRequest.logs', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='items', full_name='CompleteJobRequest.items', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=411,
)


_COMPLETEJOBRESPONSE = _descriptor.Descriptor(
  name='CompleteJobResponse',
  full_name='CompleteJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=434,
)

DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
DESCRIPTOR.message_types_by_name['GetNextJobRequest'] = _GETNEXTJOBREQUEST
DESCRIPTOR.message_types_by_name['GetNextJobResponse'] = _GETNEXTJOBRESPONSE
DESCRIPTOR.message_types_by_name['GetJobRequest'] = _GETJOBREQUEST
DESCRIPTOR.message_types_by_name['GetJobResponse'] = _GETJOBRESPONSE
DESCRIPTOR.message_types_by_name['GetJobEggRequest'] = _GETJOBEGGREQUEST
DESCRIPTOR.message_types_by_name['GetJobEggResponse'] = _GETJOBEGGRESPONSE
DESCRIPTOR.message_types_by_name['CompleteJobRequest'] = _COMPLETEJOBREQUEST
DESCRIPTOR.message_types_by_name['CompleteJobResponse'] = _COMPLETEJOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATREQUEST,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:HeartbeatRequest)
  ))
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATRESPONSE,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:HeartbeatResponse)
  ))
_sym_db.RegisterMessage(HeartbeatResponse)

GetNextJobRequest = _reflection.GeneratedProtocolMessageType('GetNextJobRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETNEXTJOBREQUEST,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:GetNextJobRequest)
  ))
_sym_db.RegisterMessage(GetNextJobRequest)

GetNextJobResponse = _reflection.GeneratedProtocolMessageType('GetNextJobResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNEXTJOBRESPONSE,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:GetNextJobResponse)
  ))
_sym_db.RegisterMessage(GetNextJobResponse)

GetJobRequest = _reflection.GeneratedProtocolMessageType('GetJobRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBREQUEST,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:GetJobRequest)
  ))
_sym_db.RegisterMessage(GetJobRequest)

GetJobResponse = _reflection.GeneratedProtocolMessageType('GetJobResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBRESPONSE,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:GetJobResponse)
  ))
_sym_db.RegisterMessage(GetJobResponse)

GetJobEggRequest = _reflection.GeneratedProtocolMessageType('GetJobEggRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBEGGREQUEST,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:GetJobEggRequest)
  ))
_sym_db.RegisterMessage(GetJobEggRequest)

GetJobEggResponse = _reflection.GeneratedProtocolMessageType('GetJobEggResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETJOBEGGRESPONSE,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:GetJobEggResponse)
  ))
_sym_db.RegisterMessage(GetJobEggResponse)

CompleteJobRequest = _reflection.GeneratedProtocolMessageType('CompleteJobRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPLETEJOBREQUEST,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:CompleteJobRequest)
  ))
_sym_db.RegisterMessage(CompleteJobRequest)

CompleteJobResponse = _reflection.GeneratedProtocolMessageType('CompleteJobResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMPLETEJOBRESPONSE,
  __module__ = 'scrapydd.grpcservice.service_pb2'
  # @@protoc_insertion_point(class_scope:CompleteJobResponse)
  ))
_sym_db.RegisterMessage(CompleteJobResponse)



_NODESERVICE = _descriptor.ServiceDescriptor(
  name='NodeService',
  full_name='NodeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=437,
  serialized_end=706,
  methods=[
  _descriptor.MethodDescriptor(
    name='Heartbeat',
    full_name='NodeService.Heartbeat',
    index=0,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_HEARTBEATRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetNextJob',
    full_name='NodeService.GetNextJob',
    index=1,
    containing_service=None,
    input_type=_GETNEXTJOBREQUEST,
    output_type=_GETNEXTJOBRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetJob',
    full_name='NodeService.GetJob',
    index=2,
    containing_service=None,
    input_type=_GETJOBREQUEST,
    output_type=_GETJOBRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEgg',
    full_name='NodeService.GetEgg',
    index=3,
    containing_service=None,
    input_type=_GETJOBEGGREQUEST,
    output_type=_GETJOBEGGREQUEST,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CompleteJob',
    full_name='NodeService.CompleteJob',
    index=4,
    containing_service=None,
    input_type=_COMPLETEJOBREQUEST,
    output_type=_COMPLETEJOBRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODESERVICE)

DESCRIPTOR.services_by_name['NodeService'] = _NODESERVICE

# @@protoc_insertion_point(module_scope)
