# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from scrapydd.grpcservice import service_pb2 as scrapydd_dot_grpcservice_dot_service__pb2


class NodeServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateNode = channel.unary_unary(
        '/NodeService/CreateNode',
        request_serializer=scrapydd_dot_grpcservice_dot_service__pb2.CreateNodeRequest.SerializeToString,
        response_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.Node.FromString,
        )
    self.CreateNodeSession = channel.unary_unary(
        '/NodeService/CreateNodeSession',
        request_serializer=scrapydd_dot_grpcservice_dot_service__pb2.CreateNodeSessionRequest.SerializeToString,
        response_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.NodeSession.FromString,
        )
    self.HeartbeatNodeSession = channel.unary_unary(
        '/NodeService/HeartbeatNodeSession',
        request_serializer=scrapydd_dot_grpcservice_dot_service__pb2.HeartbeatNodeSessionRequest.SerializeToString,
        response_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.HeartbeatNodeSessionResponse.FromString,
        )
    self.ObtainNodeSessionJob = channel.unary_unary(
        '/NodeService/ObtainNodeSessionJob',
        request_serializer=scrapydd_dot_grpcservice_dot_service__pb2.ObtainNodeSessionJobRequest.SerializeToString,
        response_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.NodeSessionJob.FromString,
        )
    self.GetNodeSessionJobEgg = channel.unary_stream(
        '/NodeService/GetNodeSessionJobEgg',
        request_serializer=scrapydd_dot_grpcservice_dot_service__pb2.GetNodeSessionJobEggRequest.SerializeToString,
        response_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.DataChunk.FromString,
        )
    self.CompleteNodeSessionJob = channel.unary_unary(
        '/NodeService/CompleteNodeSessionJob',
        request_serializer=scrapydd_dot_grpcservice_dot_service__pb2.CompleteNodeSessionJobRequest.SerializeToString,
        response_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.CompleteNodeSessionJobResponse.FromString,
        )


class NodeServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateNode(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateNodeSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HeartbeatNodeSession(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ObtainNodeSessionJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetNodeSessionJobEgg(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CompleteNodeSessionJob(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateNode': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNode,
          request_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.CreateNodeRequest.FromString,
          response_serializer=scrapydd_dot_grpcservice_dot_service__pb2.Node.SerializeToString,
      ),
      'CreateNodeSession': grpc.unary_unary_rpc_method_handler(
          servicer.CreateNodeSession,
          request_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.CreateNodeSessionRequest.FromString,
          response_serializer=scrapydd_dot_grpcservice_dot_service__pb2.NodeSession.SerializeToString,
      ),
      'HeartbeatNodeSession': grpc.unary_unary_rpc_method_handler(
          servicer.HeartbeatNodeSession,
          request_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.HeartbeatNodeSessionRequest.FromString,
          response_serializer=scrapydd_dot_grpcservice_dot_service__pb2.HeartbeatNodeSessionResponse.SerializeToString,
      ),
      'ObtainNodeSessionJob': grpc.unary_unary_rpc_method_handler(
          servicer.ObtainNodeSessionJob,
          request_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.ObtainNodeSessionJobRequest.FromString,
          response_serializer=scrapydd_dot_grpcservice_dot_service__pb2.NodeSessionJob.SerializeToString,
      ),
      'GetNodeSessionJobEgg': grpc.unary_stream_rpc_method_handler(
          servicer.GetNodeSessionJobEgg,
          request_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.GetNodeSessionJobEggRequest.FromString,
          response_serializer=scrapydd_dot_grpcservice_dot_service__pb2.DataChunk.SerializeToString,
      ),
      'CompleteNodeSessionJob': grpc.unary_unary_rpc_method_handler(
          servicer.CompleteNodeSessionJob,
          request_deserializer=scrapydd_dot_grpcservice_dot_service__pb2.CompleteNodeSessionJobRequest.FromString,
          response_serializer=scrapydd_dot_grpcservice_dot_service__pb2.CompleteNodeSessionJobResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NodeService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
